default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planning_poker_development

test:
  <<: *default
  database: planning_poker_test

production:
  <<: *default
  database: planning_poker_production
  username: planning_poker
  password: <%= ENV['PLANNING_POKER_DATABASE_PASSWORD'] %>
